query CachedQuery {
    cachedUsers{
        id,
        firstName,
        lastName,
        email,
        password,
    }
}

query NotCachedQuery{
    users{
        id,
        firstName,
        lastName,
        email,
        password,
    }
}